# Generated by Django 4.2.8 on 2023-12-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("oredered", "Ordered"), ("shipped", "Shipped")],
                default="oredered",
                max_length=20,
            ),
        ),
    ]
