# Generated by Django 4.2.8 on 2023-12-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="payment_intent",
        ),
    ]
